In [2]:
import numpy as np
import numpy.matlib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
data = pd.read_csv("churn.csv")
#check data
data.head(5)

,churn,account_length,international_plan,voicemail,number_mailmessages,totalday_minutes,total_daycalls,total_daycharge,total_eveminutes,total_evecalls,total_evecharge,total_nightminutes,total_nightcalls,total_nightcharge,total_intlminutes,total_intlcalls,total_intlcharge,number_customer_servicecalls
0,No,128,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
1,No,107,no,yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1
2,No,137,no,no,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0
3,No,84,yes,no,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2
4,No,75,yes,no,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3

In [4]:
data.columns

Index(['churn', 'account_length', 'international_plan', 'voicemail',
       'number_mailmessages', 'totalday_minutes', 'total_daycalls',
       'total_daycharge', 'total_eveminutes', 'total_evecalls',
       'total_evecharge', 'total_nightminutes', 'total_nightcalls',
       'total_nightcharge', 'total_intlminutes', 'total_intlcalls',
       'total_intlcharge', 'number_customer_servicecalls'],
      dtype='object')

In [5]:
data.dtypes

churn                            object
account_length                    int64
international_plan               object
voicemail                        object
number_mailmessages               int64
totalday_minutes                float64
total_daycalls                    int64
total_daycharge                 float64
total_eveminutes                float64
total_evecalls                    int64
total_evecharge                 float64
total_nightminutes              float64
total_nightcalls                  int64
total_nightcharge               float64
total_intlminutes               float64
total_intlcalls                   int64
total_intlcharge                float64
number_customer_servicecalls      int64
dtype: object